### ISSUE TITLE
the api is broken

### ISSUE THREAD

**Issue by bolds07** [mercadopago/sdk-nodejs#176]
**Describe the bug**
since few days ago ALL MY REQUEST ARE BEING REJECTED, no changes on my side... so someone in mercadopago backend did some shit and broken it

very simple and basic code
```
const generic = require('./generic');
const fecha = require('fecha');
const datePattern = "DD-MM-YYYY - hh:mm";

const mercadopago = require('mercadopago');
const name = "MERCADO_PAGO";
mercadopago.configure({
    client_id: '6537163865602954',
    client_secret: 'BLA BLA BLA'
});
mercadopago.ipn.manage(req).then(function(mpOrder) {
                var state = mpOrder.body.status;
                switch (state) {
                    case "pending":
                    case "in_process":
                    case "opened":
                        state = "pending";
                        break;
                    case "approved":
                        break;
                    case "rejected":
                        break;
                    case "closed":
                        return;
                        break;
                    case "cancelled":
                        state = "canceled";
                        break;
		    case "charged_back":
                    case "in_mediation":
                        state = "complain";
                        break;
                    case "refunded": 
                       state = "refunded";
                       break;
                }

                var result = {
                    orderId: mpOrder.body.external_reference,
                    status: state,
                    payer: mpOrder.body.payer
                };
                resolve(result);
            }).catch(function(error) {
                console.error("mercado pago rejected ipn message");
                console.error(error);
                reject(error);
            });

```
 
```
MercadoPagoError: Error occurred validating client_id 6537163865602954.
    at Request._callback (/srv/node_modules/mercadopago/lib/request-manager.js:320:19)
    at Request.self.callback (/srv/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/srv/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/srv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  name: 'MercadoPagoError',
  message: 'Error occurred validating client_id 6537163865602954.',
  cause: [],
  status: 400,
  idempotency: undefined }
```

**Server (please complete the following information):**
 - NodeJS Version:  node js 8
 - Operating System: FIREBASE cloud functions

**Additional context**
this code has been working for over a year.... i didnt do any change and now it got broke

**Comment by LuKks** [comment]
Try regenerating the client id/secret and using the new ones. If that doesn't works then try using directly the access_token.

I think the credentials that you are using in the code are not the same than the current ones of your MercadoPago account, anyway regenerate it sounds like a good idea.

**Comment by bolds07** [comment]
clicking at "regenerate credentials" at my dashboard DOESNT CHANGE client id nor secret... it only changes public key/acess token and i dont use them

the credentials im using in the code are 100% the same with my account they have never been changed.. im the seo, developper, owner, manager and anything else im my startup... 

so i can tell 100% sure that wasnt my mistake is someone else in the other side of the screen mistake... you might say is not your team but is someone working for mp

**Comment by bolds07** [comment]
25 errors on last 24hours... i was searching the logs the first problem was on december 19th but as it was christmas time and less costumers to my app plus im on holydays i didnt pay attention
from january 7th to now is getting more and more frequent

as i said before i work alone and make around 5k dolars a month... so you guys are costing me a lot

most of my business is automized and i never have problems because my IT team (myself) is quite amazing.... i just get troubles when some of the third party apis i use decide to update something and doesnt check for retrocompability... 
so please someone check the changelogs plus the real time logs of these requests to understand what is happening

**Comment by LuKks** [comment]
I don't actually work for anyone, either MercadoLibre/MercadoPago.
Anyway, you are right, regenerating credentials doesn't change client id/secret.

I get your point, you don't like having a code that worked perfectly fine and suddenly stop working for some nonsense reason.

"Error occurred validating client_id" is very generic, so if you want to solve it you will need to try different codes, for example, using the access_token as the README recommends it:
> We highly recomend using only the access_token. If you provide the client_id and client_secret it's going to generate the access_token anyway (only on Production, for Sandbox use access_token).

I would like to see what happens in that case.

What version of mercadopago you are using?

**Comment by LuKks** [comment]
Related issue: https://github.com/mercadopago/DEPRECATED-sdk-php/issues/148

https://www.google.com/search?q=MercadoPago+%22Error+occurred+validating+client_id%22

**Comment by LuKks** [comment]
I forgot that you can get more information about your requests and errors if you fill the form in the "Desarrolladores" section:
https://www.mercadopago.com.ar/developers/es/support
It says that it takes less than two days to get a response but they should know what is happening.

In the whiletime if you want you can test directly with `access_token` :)

**Comment by bolds07** [comment]
> Related issue: [mercadopago/DEPRECATED-sdk-php#148](https://github.com/mercadopago/DEPRECATED-sdk-php/issues/148)
> 
> https://www.google.com/search?q=MercadoPago+%22Error+occurred+validating+client_id%22

im using 1.3.0

if i consider: "Related issue: mercadopago/DEPRECATED-sdk-php#148" it means that mercado pago service is off 75% of the time... 
i get per day around 20 orders...  and 15 errors like what i reported... so it isnt just an unreliable service as it is more probable to be down than on so i really prefer to believe is not "micro unavaibilities"

i changed to access_token so will wait a few hours to see if anything changes

**Comment by bolds07** [comment]
also in this topic... on mercadopago IPN dashboard there are 3 types of request to activate.

currently "payment" type is handled by this api... any other request using `mercadopago.ipn.manage(req)` will be ignored ( i mean no response after 60 secs)

**Comment by bolds07** [comment]
also in the buglist when the payment is rejected or canceled and i query the ipn API. it replies me normally BUT the external_reference is CHANGED

my external_reference contains '_' (underscore) and on all rejections (and only at them) when i query the api to verify is the ipn request is legit and get the details the underscore has been replaced with a space

**Comment by LuKks** [comment]
> it means that mercado pago service is off 75% of the time...
> i get per day around 20 orders... and 15 errors like what i reported... so it isnt just an unreliable service as it is more probable to be down than on

I don't think so, you are experimenting 75% offline so you mean that across everyone we experiment 75% offline? That can't be unnoticed, so I prefer to think that the problem can be something related to your case (code using client id/secret + high orders/traffic).
For example, the README says that using client id/secret generates an `access_token` anyway, maybe there is a limit and you are hitting it, perhaps for that reason the recommended way is using an `access_token` directly.

> i changed to access_token so will wait a few hours to see if anything changes

What happened?

> also in this topic... on mercadopago IPN dashboard there are 3 types of request to activate.
> 
> currently "payment" type is handled by this api... any other request using `mercadopago.ipn.manage(req)` will be ignored ( i mean no response after 60 secs)

That depends on how you handle the rest of types in the code, you are missing a `res.send` in some point, for example, when `mercadopago.ipn.manage` fails.

> also in the buglist when the payment is rejected or canceled and i query the ipn API. it replies me normally BUT the external_reference is CHANGED
> 
> my external_reference contains '_' (underscore) and on all rejections (and only at them) when i query the api to verify is the ipn request is legit and get the details the underscore has been replaced with a space

Well, that's is weird, can you provide a simple reproducible code? Creating a payment and canceling it, while logging the external references.

> ... when i query the api to verify is the ipn request is legit ...

I think you can do something like this to verify the legitness of a request:
```js
function isMP (addr) {
  let ips = ['209.225.49', '216.33.197', '216.33.196', '63.128.82', '63.128.83', '63.128.94'];
  return ips.some(ip => addr.indexOf(ip + '.') !== -1);
}
```

Previously the list of ip were here: https://www.mercadopago.com.ar/developers/es/api-docs/basics/design-considerations
But the link is not working anymore, actually there is a lot of broken links.

**Comment by bolds07** [comment]
updating on this.

1- changing to access_token solved the major issue i was having

2- on the ipn topics problem my code is basicaly:

```
console.log("Mercado Pago ipn:" + JSON.stringify(req.query));
mercadopago.ipn.manage(req).then(function(mpOrder) {
                res.status(200).send("Ok");
                updateDB(mpOrder);
            }).catch(function(error) {
                console.error("mercado pago rejected ipn message");
                console.error(error);
                res.status(400).send("=[");
            });
```
      
so the only timeout that can be reached is in case the ipn.manage(req) doesn't get to resolve nor to reject...

case the topic == paymennt i pretty much get no problem, case == chargeback i always get a very fast error saying something like "invalid topic" case topic == merchant_order the code runs timeout

3- well to reproduce it is very easy:

```
var preferences = {
            items: [{title:"example",description:"desc",category_id:"category",quantity:1,currency_id:"BRL", unit_price:9.99}],
            payer: {
                name: user.name,
                email: user.email
            },
            shipments: {
                mode: 'not_specified'
            },
            external_reference: "code_123-123-123",
            expires: false,
			excluded_payment_types: [{
                    id: "ticket"
                }]
        };

mercadopago.preferences.create(preferences).then(function(mpData) {
                let ret = {
                    code: mpData.body.id,
                    url: "https://www.mercadopago.com/mlb/checkout/start?pref_id=" + mpData.body.id
                };
                resolve(ret);
            }).catch(function(mpError) {
                reject(mpError);
            });
```

so after running this code i redirect the user to the checkout url where he will only be able to pay by credit card...

so if during the payment process the card is rejected (due security, or maybe due insuficient founds) i get one ipn notification... and running the previous shown method for ipn 

mpOrder.body.external_reference will be "code 123-123-123" the underscore is converted to space and it throws an error on my database....
as i really dont care about the rejected transactions i ignore it

**Comment by LuKks** [comment]
> 1- changing to access_token solved the major issue i was having

:)

> 2- so the only timeout that can be reached is in case the ipn.manage(req) doesn't get to resolve nor to reject...
> 
> case the topic == paymennt i pretty much get no problem, case == chargeback i always get a very fast error saying something like "invalid topic" case topic == merchant_order the code runs timeout

Your `updateDB` function probably threats the `mpOrder` object always as a payment but in case of merchant_order is a different object, that is the problem. You should check to only manage the payment topic.
The chargeback is not in the available topics for `mercadopago.ipn.manage`, that's why you get a fast "invalid topic" in that case.

> 3- well to reproduce it is very easy

Sorry but that is not very reproducible (ideally just running a simple code to reproduce the error).
Anyway, why you can't use an space instead of underscore? You can actually support easily both to keep your current database compatible with old records, so I don't see big deal here.

It always had this behaviour (underscore to space) or it just started recently?
If it started recently then maybe I will try to reproduce the error to confirm it.

**Comment by Stiveknx** [comment]
If with 'mercadopago.ipn.manage'
You're getting an invalid topic.

Probably is the same issue as I do.

In my IPN url I've received the following `res.query`:
`
{ action: 'payment.created',
  api_version: 'v1',
  data: { id: '23609047' },
  date_created: '2020-01-28T23:01:34Z',
  id: 5567240842,
  live_mode: false,
  type: 'payment',
  user_id: '491614503' }
`

Well, analising https://github.com/mercadopago/dx-nodejs/blob/master/lib/resources/ipn.js

Lines 32 and 33:
`
var id = request.query.id;
var topic = request.query.topic;
`

It trys to read the topic and the id.
But we don't have that on res.query!!
That's why the "topic is invalid"

Ugly and poor, not recommended workaround (until someone fixes):

`
if(!req.query.topic) {
     let ipnResponse = await mercadopago.ipn.payment({topic: 'payment', id: req.query.data.id});
}
`
In case you want to get other topic other than 'payment', just change to whatever you need.
